# Usa una imagen base de Node.js
FROM node:20
# Especifica un directorio de trabajo para la imagen
WORKDIR /app
# Copia el package.json y package-lock.json
COPY package*.json ./
# Instala las dependencias
RUN npm install
# Copia el resto del código de la aplicación
COPY . .
#Exponemos el puerto deseado
EXPOSE 5173
# Comando por defecto para ejecutar la aplicación 
# en modo desarrollo
CMD ["npm", "run", "dev"]






