# Usa una imagen base de Node.js
FROM node:20

# Crea un directorio de trabajo
WORKDIR /app

# Copia el package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Comando por defecto para ejecutar la aplicación
CMD ["npm", "run", "dev"]