services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: proyecto_formativo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql-dev-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./Backend/.env
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: user
      DB: proyecto_formativo_db
    ports:
      - 8080:8080
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: npm start

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ./Frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

volumes:
  mysql-dev-data:

networks:
  app-network: